jobs:
  - template: common-build.yml
  - job: inclusion_test
    dependsOn: python_build
    displayName: Internal PyPI
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - download: current
        patterns: '**/*.whl'
        displayName: "Downloading all drops"
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: 'Use Python 3.8'
      - script: |
          pip install twine
        displayName: Install Twine
      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: 'Rainbow Narwhal/essex-pypi'
        displayName: Authenticate Twine
      - script: |
          cat $(PYPIRC_PATH)
          twine upload --verbose -r 'Rainbow Narwhal/essex-pypi' --config-file $(PYPIRC_PATH) $(Pipeline.Workspace)/drop*/*.whl
        displayName: Uploading to PyPI
